global:
  application_name: SimpleChatApp
  default_ec2_keyname: null
  default_platform: Tomcat 8.5 with Corretto 11 running on 64bit Amazon Linux 2
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
deploy:
  artifact: target/chatapp-1.0.0.war